# Generated by Django 5.2.8 on 2025-12-17 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_chronic_condition_user_chronic_other_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='rurality',
            new_name='imd_band',
        ),
        migrations.AddField(
            model_name='user',
            name='imd_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='post_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
