# Generated by Django 5.2.8 on 2025-11-17 01:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField()),
                ('reason', models.CharField(max_length=255)),
                ('symptoms', models.JSONField(default=list)),
                ('other_symptoms', models.CharField(blank=True, max_length=255, null=True)),
                ('risk_level', models.CharField(choices=[('pending', 'Pending'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='pending', max_length=20)),
                ('recommended_intervention', models.CharField(choices=[('pending', 'Pending'), ('sms', 'SMS reminder'), ('sms_confirm', 'SMS requiring confirmation'), ('sms_call', 'SMS + call')], default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='appointments.appointmentslot')),
            ],
            options={
                'ordering': ['-appointment_date', '-created_at'],
                'unique_together': {('patient', 'appointment_date')},
            },
        ),
    ]
