# Generated by Django 5.2.8 on 2025-11-17 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='slot',
        ),
        migrations.AddField(
            model_name='appointment',
            name='slot_id',
            field=models.IntegerField(default=1),
        ),
    ]
